// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzvppeongwhoeqmdtdyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56dnBwZW9uZ3dob2VxbWR0ZHlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTYxMTAsImV4cCI6MjA2Mjg3MjExMH0.HVGScooivJ-pFs13f_h9wo6yDUGA1xk7usLSunX9n1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);